name: Run NBA DFS R Script

on:
  schedule:
    # Weekdays 2:08 PM – 6:00 PM ET (every 30 min)
    - cron: '8,38 19-23 * * 1-5'
    
    # Weekdays 6:08 PM – 10:13 PM ET (every 15 min)
    - cron: '8,23,38,53 23 * * 1-5'
    - cron: '8,23,38,53 0-3 * * 2-6'
    
    # Saturdays 12:08 PM – 10:13 PM ET (every 15 min)
    - cron: '8,23,38,53 17-23 * * 6'
    - cron: '8,23,38,53 0-4 * * 0'
    
    # Sundays 10:08 AM – 10:13 PM ET (every 15 min)
    - cron: '8,23,38,53 15-23 * * 0'
    - cron: '8,23,38,53 0-4 * * 1'

#on: march-oct schedule
  #schedule:
    # Weekdays 2:08 PM – 6:00 PM ET (every 30 min)
    #- cron: '8,38 19-23 * * 1-5'
    
    # Weekdays 6:08 PM – 10:13 PM ET (every 15 min, with gap 7:53-7:58)
    #- cron: '8,23,38,53 23 * * 1-5'
    #- cron: '8,23,38,53 0-3 * * 2-6'
    #- cron: '8,23 4 * * 2-6'
    
    # Saturdays 12:08 PM – 10:13 PM ET (every 15 min)
    #- cron: '8,23,38,53 17-23 * * 6'
    #- cron: '8,23,38,53 0-4 * * 0'
    
    # Sundays 10:08 AM – 10:13 PM ET (every 15 min)
    #- cron: '8,23,38,53 15-23 * * 0'
    #- cron: '8,23,38,53 0-4 * * 1'

  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Cache R packages
      uses: actions/cache@v3
      with:
        path: ${{ env.R_LIBS_USER }}
        key: ${{ runner.os }}-r-${{ hashFiles('**/*.lock') }}
        restore-keys: |
          ${{ runner.os }}-r-

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

    - name: Install R packages
      run: |
        Rscript -e "install.packages(c('googlesheets4', 'googledrive', 'dplyr', 'lubridate', 'stringr', 'rjson', 'httr', 'base64enc', 'magrittr', 'plyr', 'RCurl', 'XML'), repos = 'https://cloud.r-project.org')"

    - name: Check installed R packages
      run: |
        Rscript -e 'cat("Loaded packages:\n"); print(.packages())'
    
    - name: Run R script
      env:
        GCP_SHEETS_KEY_B64: ${{ secrets.GCP_SHEETS_KEY_B64 }}
      run: |
        Rscript "NBA DFS.R"
